# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DevBootcampHackathon' do

end

target 'DevBootcampHackathonTests' do

end

target 'DevBootcampHackathonUITests' do

end

